[book]
title = "Wormhole Development Book"
authors = [
    "Dev Bharel"
]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url="https://github.com/wormhole-foundation/xdapp-book"
default-theme= "ayu"
additional-js = ["src/static/solidity.min.js"]
